# Generated by Django 6.0.2 on 2026-02-25 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        ('investigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_date', models.DateTimeField(auto_now_add=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trial', to='cases.case')),
                ('judge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='judgments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Verdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_guilty', models.BooleanField()),
                ('punishment_title', models.CharField(blank=True, max_length=255, null=True)),
                ('punishment_description', models.TextField(blank=True, null=True)),
                ('suspect', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='investigation.suspect')),
                ('trial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verdicts', to='trials.trial')),
            ],
        ),
    ]
