# Generated by Django 6.0.2 on 2026-02-26 21:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interrogation',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='متن بازجویی'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='detective_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='sergeant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sergeant_interrogations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='sergeant_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
