# Generated by Django 6.0.2 on 2026-02-27 00:25

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investigation', '0002_interrogation_transcript_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bail',
            name='payment_ref',
        ),
        migrations.AddField(
            model_name='bail',
            name='assigned_by',
            field=models.ForeignKey(limit_choices_to={'role': 'sergeant'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspect',
            name='crime_level',
            field=models.IntegerField(choices=[(1, 'سطح ۱ - خشن (Violent)'), (2, 'سطح ۲ - مالی (Financial)'), (3, 'سطح ۳ - سبک (Light)')], default=3),
        ),
        migrations.AlterField(
            model_name='bail',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ به ریال'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='captain_verdict',
            field=models.BooleanField(blank=True, null=True, verbose_name='تایید کاپیتان'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='chief_verdict',
            field=models.BooleanField(blank=True, null=True, verbose_name='تایید رئیس پلیس'),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='detective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='det_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='detective_score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='sergeant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='serg_reports', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='sergeant_score',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='interrogation',
            name='transcript',
            field=models.TextField(blank=True, null=True, verbose_name='گزارش بازجویی و اعترافات'),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='status',
            field=models.CharField(choices=[('suspect', 'مظنون (Suspect)'), ('wanted', 'تحت تعقیب (Wanted)'), ('arrested', 'بازداشتی (Arrested)'), ('convicted', 'مجرم (Convicted)'), ('cleared', 'تبرئه شده (Cleared)')], default='suspect', max_length=20),
        ),
        migrations.AlterField(
            model_name='suspect',
            name='wanted_since',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
