# Generated by Django 6.0.2 on 2026-02-25 11:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investigation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('rejected_officer', 'Rejected Officer'), ('approved_officer', 'Approved Officer'), ('rejected_detective', 'Rejected Detective'), ('approved', 'Approved')], default='pending', max_length=30)),
                ('unique_code', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_claims', to=settings.AUTH_USER_MODEL)),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_rewards', to='investigation.suspect')),
            ],
        ),
    ]
