# Generated by Django 6.0.2 on 2026-02-25 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectiveBoardNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, null=True)),
                ('pos_x', models.FloatField(default=0.0)),
                ('pos_y', models.FloatField(default=0.0)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_nodes', to='cases.case')),
            ],
        ),
        migrations.CreateModel(
            name='DetectiveBoardEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_edges', to='cases.case')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='evidences.detectiveboardnode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='evidences.detectiveboardnode')),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('evidence_type', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='cases.case')),
                ('recorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='detectiveboardnode',
            name='evidence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='evidences.evidence'),
        ),
        migrations.CreateModel(
            name='BioEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coroner_approved', models.BooleanField(blank=True, null=True)),
                ('db_result', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio_detail', to='evidences.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='IDEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_detail', to='evidences.evidence')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('plate_number', models.CharField(blank=True, max_length=20, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle_detail', to='evidences.evidence')),
            ],
        ),
    ]
